<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\uBeac.Models\uBeac.Models.csproj" />
    <ProjectReference Include="..\uBeac.Repositories.MongoDB\uBeac.Repositories.MongoDB.csproj" />
  </ItemGroup>

</Project>
