<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
    <UseAppHost>true</UseAppHost>
    <SelfContained>false</SelfContained>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
    <LangVersion>7.1</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Properties\PublishProfiles\**" />
    <EmbeddedResource Remove="Properties\PublishProfiles\**" />
    <None Remove="Properties\PublishProfiles\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Components\uBeac.Hosted.Service\uBeac.Hosted.Service.csproj" />
    <ProjectReference Include="..\..\Components\uBeac.IoT.Processing\uBeac.IoT.Processing.csproj" />
    <ProjectReference Include="..\..\Components\uBeac.Logging\uBeac.Logging.csproj" />
    <ProjectReference Include="..\..\Components\uBeac.Messaging\uBeac.Messaging.csproj" />
    <ProjectReference Include="..\..\Components\uBeac.Models\uBeac.Models.csproj" />
    <ProjectReference Include="..\..\Components\uBeac.Repositories.MongoDB\uBeac.Repositories.MongoDB.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.Nightly.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
