<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <LangVersion>7.1</LangVersion>
    <UserSecretsId>7fee4bf3-1db9-4eb0-b6ac-343c14a66357</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\**" />
    <Content Remove="Views\**" />
    <EmbeddedResource Remove="Views\**" />
    <None Remove="Views\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IPAddressRange" Version="3.2.1" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Components\uBeac.Common\uBeac.Common.csproj" />
    <ProjectReference Include="..\..\Components\uBeac.Mappings\uBeac.Mappings.csproj" />
    <ProjectReference Include="..\..\Components\uBeac.Models\uBeac.Models.csproj" />
    <ProjectReference Include="..\..\Components\uBeac.Repositories.MongoDB\uBeac.Repositories.MongoDB.csproj" />
    <ProjectReference Include="..\..\Components\uBeac.Security\uBeac.Security.csproj" />
    <ProjectReference Include="..\..\Components\uBeac.Services.Email\uBeac.Services.Email.csproj" />
    <ProjectReference Include="..\..\Components\uBeac.Storage.File\uBeac.Storage.File.csproj" />
    <ProjectReference Include="..\..\Components\uBeac.Web.Documentation\uBeac.Web.Documentation.csproj" />
    <ProjectReference Include="..\..\Components\uBeac.Web\uBeac.Web.csproj" />
  </ItemGroup>

</Project>
